/**
 * LLM Domain Introspection
 *
 * A programmatic, JSON-serializable description of every LLM command — its
 * roles, per-language markers, and a runnable example in each supported
 * language. Lets docs, the MCP server, and LLM agents discover "what can I
 * express?" from a single source of truth instead of hand-maintaining
 * examples in three places.
 *
 * @example
 * ```typescript
 * import { describeCommands } from '@lokascript/domain-llm';
 *
 * for (const cmd of describeCommands()) {
 *   console.log(cmd.action, '→', cmd.examples.ja);
 * }
 * // ask → #article から "What is this?" 聞く
 * ```
 */

import type { CommandSchema, RoleSpec } from '@lokascript/framework';
import { allSchemas } from './schemas/index.js';

/**
 * Language codes supported by the LLM DSL, in priority order.
 * Shared by introspection and any consumer that needs the full set.
 */
export const LLM_LANGUAGE_CODES = ['en', 'es', 'ja', 'ar', 'ko', 'zh', 'tr', 'fr'] as const;

export type LLMLanguageCode = (typeof LLM_LANGUAGE_CODES)[number];

// =============================================================================
// Public Types
// =============================================================================

/** Description of a single semantic role within a command. */
export interface RoleDescription {
  /** Semantic role name (patient, source, manner, …). */
  role: string;
  /** Human-readable description of what the role captures. */
  description: string;
  /** Whether the command requires this role. */
  required: boolean;
  /** Accepted semantic value types (literal, selector, expression, …). */
  expectedTypes: string[];
  /** Per-language marker keyword for this role (lang code → keyword). */
  markers: Record<string, string>;
}

/** Full description of one LLM command. */
export interface CommandDescription {
  /** Command action (ask, summarize, analyze, translate). */
  action: string;
  /** Human-readable description of the command. */
  description: string;
  /** Schema category (always `llm` here). */
  category: string;
  /** The role treated as the command's primary argument. */
  primaryRole: string;
  /** All roles the command accepts. */
  roles: RoleDescription[];
  /** A runnable example invocation per language (lang code → DSL command). */
  examples: Record<string, string>;
}

// =============================================================================
// Verified Examples
// =============================================================================

/**
 * One runnable example per command per language. Every entry uses identical
 * role *content* (same selectors / literals) — only keywords, markers, and
 * word order differ — so all 8 forms of a command compile to byte-identical
 * `LLMPromptSpec` JSON.
 *
 * These are hand-authored and verified (see introspection.test.ts, which
 * round-trips every entry through `compile()`). They are not generated by
 * `renderLLM`: that renderer's SOV (ja/ko/tr) word order does not currently
 * round-trip for every command, so a verified table is the reliable source.
 */
const COMMAND_EXAMPLES: Record<string, Record<LLMLanguageCode, string>> = {
  ask: {
    en: 'ask "What is this?" from #article',
    es: 'preguntar "What is this?" de #article',
    ja: '#article から "What is this?" 聞く',
    ar: 'اسأل "What is this?" من #article',
    ko: '#article 에서 "What is this?" 질문',
    zh: '提问 "What is this?" 从 #article',
    tr: '#article dan "What is this?" sor',
    fr: 'demander "What is this?" de #article',
  },
  summarize: {
    en: 'summarize #document',
    es: 'resumir #document',
    ja: '#document 要約',
    ar: 'لخّص #document',
    ko: '#document 요약',
    zh: '总结 #document',
    tr: '#document özetle',
    fr: 'résumer #document',
  },
  analyze: {
    en: 'analyze #review as sentiment',
    es: 'analizar #review como sentiment',
    ja: 'として sentiment #review 分析',
    ar: 'حلّل #review ك sentiment',
    ko: 'sentiment 로 #review 분석',
    zh: '分析 #review 以 sentiment',
    tr: 'sentiment olarak #review çözümle',
    fr: 'analyser #review comme sentiment',
  },
  translate: {
    en: 'translate #text from english to japanese',
    es: 'traducir #text de english a japanese',
    ja: '#text english から japanese に 翻訳',
    ar: 'ترجم #text من english إلى japanese',
    ko: '#text english 에서 japanese 로 번역',
    zh: '翻译 #text 从 english 到 japanese',
    tr: '#text english dan japanese e çevir',
    fr: 'traduire #text de english vers japanese',
  },
};

// =============================================================================
// Internal Helpers
// =============================================================================

/** Convert a RoleSpec to its serializable description. */
function roleToDescription(role: RoleSpec): RoleDescription {
  return {
    role: role.role,
    description: role.description,
    required: role.required,
    expectedTypes: [...role.expectedTypes],
    markers: { ...(role.markerOverride ?? {}) },
  };
}

/** Convert a CommandSchema to its full description. */
function describeSchema(schema: CommandSchema): CommandDescription {
  return {
    action: schema.action,
    description: schema.description,
    category: schema.category,
    primaryRole: schema.primaryRole,
    roles: schema.roles.map(roleToDescription),
    examples: { ...(COMMAND_EXAMPLES[schema.action] ?? {}) },
  };
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Describe every LLM command — roles, per-language markers, and a runnable
 * example in each supported language. The result is plain JSON-serializable
 * data.
 */
export function describeCommands(): CommandDescription[] {
  return allSchemas.map(describeSchema);
}

/**
 * Describe a single LLM command by action name, or `undefined` if no such
 * command exists.
 */
export function describeCommand(action: string): CommandDescription | undefined {
  const schema = allSchemas.find(s => s.action === action);
  return schema ? describeSchema(schema) : undefined;
}
