import type { LearnLanguageProfile } from '../types';

export const arProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'ar',
    wordOrder: 'VSO',
    keywords: {
      add: { primary: 'أضف' },
      remove: { primary: 'احذف' },
      toggle: { primary: 'بدّل' },
      put: { primary: 'ضع' },
      set: { primary: 'عيّن' },
      show: { primary: 'أظهر' },
      hide: { primary: 'أخفِ' },
      get: { primary: 'احصل' },
      wait: { primary: 'انتظر' },
      fetch: { primary: 'أحضر' },
      send: { primary: 'أرسل' },
      go: { primary: 'اذهب' },
      increment: { primary: 'زد' },
      decrement: { primary: 'أنقص' },
      take: { primary: 'خذ' },
    },
  },
  morphologyTable: {
    add: {
      root: 'ض-ي-ف',
      form: 'IV',
      past: {
        howa: 'أضافَ',
        hiya: 'أضافَت',
        anta: 'أضَفتَ',
        anti: 'أضَفتِ',
        ana: 'أضَفتُ',
        hum: 'أضافوا',
        nahnu: 'أضَفنا',
      },
      present: {
        howa: 'يُضيفُ',
        hiya: 'تُضيفُ',
        anta: 'تُضيفُ',
        anti: 'تُضيفينَ',
        ana: 'أُضيفُ',
        hum: 'يُضيفونَ',
        nahnu: 'نُضيفُ',
      },
      imperative: {
        ms: 'أضِف',
        fs: 'أضيفي',
        mp: 'أضيفوا',
      },
      activeParticiple: 'مُضيف',
      passiveParticiple: 'مُضاف',
      masdar: 'إضافة',
    },
    remove: {
      root: 'ح-ذ-ف',
      form: 'I',
      past: {
        howa: 'حَذَفَ',
        hiya: 'حَذَفَت',
        anta: 'حَذَفتَ',
        anti: 'حَذَفتِ',
        ana: 'حَذَفتُ',
        hum: 'حَذَفوا',
        nahnu: 'حَذَفنا',
      },
      present: {
        howa: 'يَحذِفُ',
        hiya: 'تَحذِفُ',
        anta: 'تَحذِفُ',
        anti: 'تَحذِفينَ',
        ana: 'أَحذِفُ',
        hum: 'يَحذِفونَ',
        nahnu: 'نَحذِفُ',
      },
      imperative: {
        ms: 'احذِف',
        fs: 'احذِفي',
        mp: 'احذِفوا',
      },
      activeParticiple: 'حاذِف',
      passiveParticiple: 'مَحذوف',
      masdar: 'حَذف',
    },
    toggle: {
      root: 'ب-د-ل',
      form: 'II',
      past: {
        howa: 'بَدَّلَ',
        hiya: 'بَدَّلَت',
        anta: 'بَدَّلتَ',
        anti: 'بَدَّلتِ',
        ana: 'بَدَّلتُ',
        hum: 'بَدَّلوا',
        nahnu: 'بَدَّلنا',
      },
      present: {
        howa: 'يُبَدِّلُ',
        hiya: 'تُبَدِّلُ',
        anta: 'تُبَدِّلُ',
        anti: 'تُبَدِّلينَ',
        ana: 'أُبَدِّلُ',
        hum: 'يُبَدِّلونَ',
        nahnu: 'نُبَدِّلُ',
      },
      imperative: {
        ms: 'بَدِّل',
        fs: 'بَدِّلي',
        mp: 'بَدِّلوا',
      },
      activeParticiple: 'مُبَدِّل',
      passiveParticiple: 'مُبَدَّل',
      masdar: 'تبديل',
    },
    put: {
      root: 'و-ض-ع',
      form: 'I',
      past: {
        howa: 'وَضَعَ',
        hiya: 'وَضَعَت',
        anta: 'وَضَعتَ',
        anti: 'وَضَعتِ',
        ana: 'وَضَعتُ',
        hum: 'وَضَعوا',
        nahnu: 'وَضَعنا',
      },
      present: {
        howa: 'يَضَعُ',
        hiya: 'تَضَعُ',
        anta: 'تَضَعُ',
        anti: 'تَضَعينَ',
        ana: 'أَضَعُ',
        hum: 'يَضَعونَ',
        nahnu: 'نَضَعُ',
      },
      imperative: {
        ms: 'ضَع',
        fs: 'ضَعي',
        mp: 'ضَعوا',
      },
      activeParticiple: 'واضِع',
      passiveParticiple: 'مَوضوع',
      masdar: 'وَضع',
    },
    set: {
      root: 'ع-ي-ن',
      form: 'II',
      past: {
        howa: 'عَيَّنَ',
        hiya: 'عَيَّنَت',
        anta: 'عَيَّنتَ',
        anti: 'عَيَّنتِ',
        ana: 'عَيَّنتُ',
        hum: 'عَيَّنوا',
        nahnu: 'عَيَّنا',
      },
      present: {
        howa: 'يُعَيِّنُ',
        hiya: 'تُعَيِّنُ',
        anta: 'تُعَيِّنُ',
        anti: 'تُعَيِّنينَ',
        ana: 'أُعَيِّنُ',
        hum: 'يُعَيِّنونَ',
        nahnu: 'نُعَيِّنُ',
      },
      imperative: {
        ms: 'عَيِّن',
        fs: 'عَيِّني',
        mp: 'عَيِّنوا',
      },
      activeParticiple: 'مُعَيِّن',
      passiveParticiple: 'مُعَيَّن',
      masdar: 'تعيين',
    },
    show: {
      root: 'ظ-ه-ر',
      form: 'IV',
      past: {
        howa: 'أظهَرَ',
        hiya: 'أظهَرَت',
        anta: 'أظهَرتَ',
        anti: 'أظهَرتِ',
        ana: 'أظهَرتُ',
        hum: 'أظهَروا',
        nahnu: 'أظهَرنا',
      },
      present: {
        howa: 'يُظهِرُ',
        hiya: 'تُظهِرُ',
        anta: 'تُظهِرُ',
        anti: 'تُظهِرينَ',
        ana: 'أُظهِرُ',
        hum: 'يُظهِرونَ',
        nahnu: 'نُظهِرُ',
      },
      imperative: {
        ms: 'أظهِر',
        fs: 'أظهِري',
        mp: 'أظهِروا',
      },
      activeParticiple: 'مُظهِر',
      passiveParticiple: 'مُظهَر',
      masdar: 'إظهار',
    },
    hide: {
      root: 'خ-ف-ي',
      form: 'IV',
      past: {
        howa: 'أخفى',
        hiya: 'أخفَت',
        anta: 'أخفَيتَ',
        anti: 'أخفَيتِ',
        ana: 'أخفَيتُ',
        hum: 'أخفَوا',
        nahnu: 'أخفَينا',
      },
      present: {
        howa: 'يُخفي',
        hiya: 'تُخفي',
        anta: 'تُخفي',
        anti: 'تُخفينَ',
        ana: 'أُخفي',
        hum: 'يُخفونَ',
        nahnu: 'نُخفي',
      },
      imperative: {
        ms: 'أخفِ',
        fs: 'أخفي',
        mp: 'أخفوا',
      },
      activeParticiple: 'مُخفٍ',
      passiveParticiple: 'مُخفى',
      masdar: 'إخفاء',
    },
    get: {
      root: 'ح-ص-ل',
      form: 'I',
      past: {
        howa: 'حَصَلَ',
        hiya: 'حَصَلَت',
        anta: 'حَصَلتَ',
        anti: 'حَصَلتِ',
        ana: 'حَصَلتُ',
        hum: 'حَصَلوا',
        nahnu: 'حَصَلنا',
      },
      present: {
        howa: 'يَحصُلُ',
        hiya: 'تَحصُلُ',
        anta: 'تَحصُلُ',
        anti: 'تَحصُلينَ',
        ana: 'أَحصُلُ',
        hum: 'يَحصُلونَ',
        nahnu: 'نَحصُلُ',
      },
      imperative: {
        ms: 'احصُل',
        fs: 'احصُلي',
        mp: 'احصُلوا',
      },
      activeParticiple: 'حاصِل',
      passiveParticiple: 'مَحصول',
      masdar: 'حُصول',
    },
    wait: {
      root: 'ن-ظ-ر',
      form: 'VIII',
      past: {
        howa: 'انتَظَرَ',
        hiya: 'انتَظَرَت',
        anta: 'انتَظَرتَ',
        anti: 'انتَظَرتِ',
        ana: 'انتَظَرتُ',
        hum: 'انتَظَروا',
        nahnu: 'انتَظَرنا',
      },
      present: {
        howa: 'يَنتَظِرُ',
        hiya: 'تَنتَظِرُ',
        anta: 'تَنتَظِرُ',
        anti: 'تَنتَظِرينَ',
        ana: 'أَنتَظِرُ',
        hum: 'يَنتَظِرونَ',
        nahnu: 'نَنتَظِرُ',
      },
      imperative: {
        ms: 'انتَظِر',
        fs: 'انتَظِري',
        mp: 'انتَظِروا',
      },
      activeParticiple: 'مُنتَظِر',
      passiveParticiple: 'مُنتَظَر',
      masdar: 'انتِظار',
    },
    fetch: {
      root: 'ح-ض-ر',
      form: 'IV',
      past: {
        howa: 'أحضَرَ',
        hiya: 'أحضَرَت',
        anta: 'أحضَرتَ',
        anti: 'أحضَرتِ',
        ana: 'أحضَرتُ',
        hum: 'أحضَروا',
        nahnu: 'أحضَرنا',
      },
      present: {
        howa: 'يُحضِرُ',
        hiya: 'تُحضِرُ',
        anta: 'تُحضِرُ',
        anti: 'تُحضِرينَ',
        ana: 'أُحضِرُ',
        hum: 'يُحضِرونَ',
        nahnu: 'نُحضِرُ',
      },
      imperative: {
        ms: 'أحضِر',
        fs: 'أحضِري',
        mp: 'أحضِروا',
      },
      activeParticiple: 'مُحضِر',
      passiveParticiple: 'مُحضَر',
      masdar: 'إحضار',
    },
    send: {
      root: 'ر-س-ل',
      form: 'IV',
      past: {
        howa: 'أرسَلَ',
        hiya: 'أرسَلَت',
        anta: 'أرسَلتَ',
        anti: 'أرسَلتِ',
        ana: 'أرسَلتُ',
        hum: 'أرسَلوا',
        nahnu: 'أرسَلنا',
      },
      present: {
        howa: 'يُرسِلُ',
        hiya: 'تُرسِلُ',
        anta: 'تُرسِلُ',
        anti: 'تُرسِلينَ',
        ana: 'أُرسِلُ',
        hum: 'يُرسِلونَ',
        nahnu: 'نُرسِلُ',
      },
      imperative: {
        ms: 'أرسِل',
        fs: 'أرسِلي',
        mp: 'أرسِلوا',
      },
      activeParticiple: 'مُرسِل',
      passiveParticiple: 'مُرسَل',
      masdar: 'إرسال',
    },
    go: {
      root: 'ذ-ه-ب',
      form: 'I',
      past: {
        howa: 'ذَهَبَ',
        hiya: 'ذَهَبَت',
        anta: 'ذَهَبتَ',
        anti: 'ذَهَبتِ',
        ana: 'ذَهَبتُ',
        hum: 'ذَهَبوا',
        nahnu: 'ذَهَبنا',
      },
      present: {
        howa: 'يَذهَبُ',
        hiya: 'تَذهَبُ',
        anta: 'تَذهَبُ',
        anti: 'تَذهَبينَ',
        ana: 'أَذهَبُ',
        hum: 'يَذهَبونَ',
        nahnu: 'نَذهَبُ',
      },
      imperative: {
        ms: 'اذهَب',
        fs: 'اذهَبي',
        mp: 'اذهَبوا',
      },
      activeParticiple: 'ذاهِب',
      passiveParticiple: 'مَذهوب',
      masdar: 'ذَهاب',
    },
    increment: {
      root: 'ز-ي-د',
      form: 'I',
      past: {
        howa: 'زادَ',
        hiya: 'زادَت',
        anta: 'زِدتَ',
        anti: 'زِدتِ',
        ana: 'زِدتُ',
        hum: 'زادوا',
        nahnu: 'زِدنا',
      },
      present: {
        howa: 'يَزيدُ',
        hiya: 'تَزيدُ',
        anta: 'تَزيدُ',
        anti: 'تَزيدينَ',
        ana: 'أَزيدُ',
        hum: 'يَزيدونَ',
        nahnu: 'نَزيدُ',
      },
      imperative: {
        ms: 'زِد',
        fs: 'زيدي',
        mp: 'زيدوا',
      },
      activeParticiple: 'زائِد',
      passiveParticiple: 'مَزيد',
      masdar: 'زِيادة',
    },
    decrement: {
      root: 'ن-ق-ص',
      form: 'IV',
      past: {
        howa: 'أنقَصَ',
        hiya: 'أنقَصَت',
        anta: 'أنقَصتَ',
        anti: 'أنقَصتِ',
        ana: 'أنقَصتُ',
        hum: 'أنقَصوا',
        nahnu: 'أنقَصنا',
      },
      present: {
        howa: 'يُنقِصُ',
        hiya: 'تُنقِصُ',
        anta: 'تُنقِصُ',
        anti: 'تُنقِصينَ',
        ana: 'أُنقِصُ',
        hum: 'يُنقِصونَ',
        nahnu: 'نُنقِصُ',
      },
      imperative: {
        ms: 'أنقِص',
        fs: 'أنقِصي',
        mp: 'أنقِصوا',
      },
      activeParticiple: 'مُنقِص',
      passiveParticiple: 'مُنقَص',
      masdar: 'إنقاص',
    },
    take: {
      root: 'أ-خ-ذ',
      form: 'I',
      past: {
        howa: 'أخَذَ',
        hiya: 'أخَذَت',
        anta: 'أخَذتَ',
        anti: 'أخَذتِ',
        ana: 'أخَذتُ',
        hum: 'أخَذوا',
        nahnu: 'أخَذنا',
      },
      present: {
        howa: 'يَأخُذُ',
        hiya: 'تَأخُذُ',
        anta: 'تَأخُذُ',
        anti: 'تَأخُذينَ',
        ana: 'آخُذُ',
        hum: 'يَأخُذونَ',
        nahnu: 'نَأخُذُ',
      },
      imperative: {
        ms: 'خُذ',
        fs: 'خُذي',
        mp: 'خُذوا',
      },
      activeParticiple: 'آخِذ',
      passiveParticiple: 'مَأخوذ',
      masdar: 'أخذ',
    },
  },
  frames: {
    code: 'ar',
    wordOrder: 'VSO',
    frames: [
      {
        function: 'commanding',
        template: '{verb.imperative.ms} {patient} {target}',
        verbForm: 'imperative.ms',
        example: 'أضِف .active إلى #button',
      },
      {
        function: 'describing',
        template: '{verb.present.howa} {subject} {patient} {target}',
        verbForm: 'present.howa',
        example: 'يُضيفُ النظامُ .active إلى #button',
      },
      {
        function: 'narrating',
        template: '{verb.past.howa} {subject} {patient} {target}',
        verbForm: 'past.howa',
        example: 'أضافَ النظامُ .active إلى #button',
      },
      {
        function: 'questioning',
        template: 'هل {verb.past.howa} {subject} {patient} {target}؟',
        verbForm: 'past.howa',
        example: 'هل أضافَ النظامُ .active إلى #button؟',
      },
      {
        function: 'negating',
        template: 'لم {verb.present.howa} {subject} {patient} {target}',
        verbForm: 'present.howa',
        example: 'لم يُضِف النظامُ .active إلى #button',
      },
      {
        function: 'planning',
        template: 'سوف {verb.present.howa} {subject} {patient} {target}',
        verbForm: 'present.howa',
        example: 'سوف يُضيفُ النظامُ .active إلى #button',
      },
      {
        function: 'progressing',
        template: '{subject} {verb.activeParticiple} {patient} {target}',
        verbForm: 'activeParticiple',
        example: 'النظامُ مُضيفٌ .active إلى #button',
      },
    ],
  },
  defaultSubject: 'النظامُ',
};
