import type { LearnLanguageProfile } from '../types';

export const enProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'en',
    wordOrder: 'SVO',
    keywords: {
      add: { primary: 'add' },
      remove: { primary: 'remove' },
      toggle: { primary: 'toggle' },
      put: { primary: 'put' },
      set: { primary: 'set' },
      show: { primary: 'show' },
      hide: { primary: 'hide' },
      get: { primary: 'get' },
      wait: { primary: 'wait' },
      fetch: { primary: 'fetch' },
      send: { primary: 'send' },
      go: { primary: 'go' },
      increment: { primary: 'increment' },
      decrement: { primary: 'decrement' },
      take: { primary: 'take' },
    },
  },
  morphologyTable: {
    add: {
      base: 'add',
      thirdPerson: 'adds',
      past: 'added',
      pastParticiple: 'added',
      presentParticiple: 'adding',
    },
    remove: {
      base: 'remove',
      thirdPerson: 'removes',
      past: 'removed',
      pastParticiple: 'removed',
      presentParticiple: 'removing',
    },
    toggle: {
      base: 'toggle',
      thirdPerson: 'toggles',
      past: 'toggled',
      pastParticiple: 'toggled',
      presentParticiple: 'toggling',
    },
    put: {
      base: 'put',
      thirdPerson: 'puts',
      past: 'put',
      pastParticiple: 'put',
      presentParticiple: 'putting',
    },
    set: {
      base: 'set',
      thirdPerson: 'sets',
      past: 'set',
      pastParticiple: 'set',
      presentParticiple: 'setting',
    },
    show: {
      base: 'show',
      thirdPerson: 'shows',
      past: 'showed',
      pastParticiple: 'shown',
      presentParticiple: 'showing',
    },
    hide: {
      base: 'hide',
      thirdPerson: 'hides',
      past: 'hid',
      pastParticiple: 'hidden',
      presentParticiple: 'hiding',
    },
    get: {
      base: 'get',
      thirdPerson: 'gets',
      past: 'got',
      pastParticiple: 'gotten',
      presentParticiple: 'getting',
    },
    wait: {
      base: 'wait',
      thirdPerson: 'waits',
      past: 'waited',
      pastParticiple: 'waited',
      presentParticiple: 'waiting',
    },
    fetch: {
      base: 'fetch',
      thirdPerson: 'fetches',
      past: 'fetched',
      pastParticiple: 'fetched',
      presentParticiple: 'fetching',
    },
    send: {
      base: 'send',
      thirdPerson: 'sends',
      past: 'sent',
      pastParticiple: 'sent',
      presentParticiple: 'sending',
    },
    go: {
      base: 'go',
      thirdPerson: 'goes',
      past: 'went',
      pastParticiple: 'gone',
      presentParticiple: 'going',
    },
    increment: {
      base: 'increment',
      thirdPerson: 'increments',
      past: 'incremented',
      pastParticiple: 'incremented',
      presentParticiple: 'incrementing',
    },
    decrement: {
      base: 'decrement',
      thirdPerson: 'decrements',
      past: 'decremented',
      pastParticiple: 'decremented',
      presentParticiple: 'decrementing',
    },
    take: {
      base: 'take',
      thirdPerson: 'takes',
      past: 'took',
      pastParticiple: 'taken',
      presentParticiple: 'taking',
    },
  },
  frames: {
    code: 'en',
    wordOrder: 'SVO',
    frames: [
      {
        function: 'commanding',
        template: '{verb.base} {patient} {target}',
        verbForm: 'base',
        example: 'add .active to #button',
      },
      {
        function: 'describing',
        template: '{subject} {verb.thirdPerson} {patient} {target}',
        verbForm: 'thirdPerson',
        example: 'The system adds .active to #button',
      },
      {
        function: 'narrating',
        template: '{subject} {verb.past} {patient} {target}',
        verbForm: 'past',
        example: 'The system added .active to #button',
      },
      {
        function: 'questioning',
        template: 'Did {subject} {verb.base} {patient} {target}?',
        verbForm: 'base',
        example: 'Did the system add .active to #button?',
      },
      {
        function: 'negating',
        template: '{subject} did not {verb.base} {patient} {target}',
        verbForm: 'base',
        example: 'The system did not add .active to #button',
      },
      {
        function: 'planning',
        template: '{subject} will {verb.base} {patient} {target}',
        verbForm: 'base',
        example: 'The system will add .active to #button',
      },
      {
        function: 'progressing',
        template: '{subject} is {verb.presentParticiple} {patient} {target}',
        verbForm: 'presentParticiple',
        example: 'The system is adding .active to #button',
      },
    ],
  },
  defaultSubject: 'the system',
};
