import type { LearnLanguageProfile, SpanishForms, LanguageFrames } from '../types';

const morphologyTable: Record<string, SpanishForms> = {
  add: {
    infinitive: 'agregar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'agrego',
      tu: 'agregas',
      el: 'agrega',
      nosotros: 'agregamos',
      vosotros: 'agregáis',
      ellos: 'agregan',
    },
    preterite: {
      yo: 'agregué',
      tu: 'agregaste',
      el: 'agregó',
      nosotros: 'agregamos',
      vosotros: 'agregasteis',
      ellos: 'agregaron',
    },
    imperfect: {
      yo: 'agregaba',
      tu: 'agregabas',
      el: 'agregaba',
      nosotros: 'agregábamos',
      vosotros: 'agregabais',
      ellos: 'agregaban',
    },
    future: {
      yo: 'agregaré',
      tu: 'agregarás',
      el: 'agregará',
      nosotros: 'agregaremos',
      vosotros: 'agregaréis',
      ellos: 'agregarán',
    },
    imperative: {
      tu: 'agrega',
      usted: 'agregue',
      ustedes: 'agreguen',
    },
    gerund: 'agregando',
    pastParticiple: {
      ms: 'agregado',
      fs: 'agregada',
      mp: 'agregados',
      fp: 'agregadas',
    },
  },

  remove: {
    infinitive: 'quitar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'quito',
      tu: 'quitas',
      el: 'quita',
      nosotros: 'quitamos',
      vosotros: 'quitáis',
      ellos: 'quitan',
    },
    preterite: {
      yo: 'quité',
      tu: 'quitaste',
      el: 'quitó',
      nosotros: 'quitamos',
      vosotros: 'quitasteis',
      ellos: 'quitaron',
    },
    imperfect: {
      yo: 'quitaba',
      tu: 'quitabas',
      el: 'quitaba',
      nosotros: 'quitábamos',
      vosotros: 'quitabais',
      ellos: 'quitaban',
    },
    future: {
      yo: 'quitaré',
      tu: 'quitarás',
      el: 'quitará',
      nosotros: 'quitaremos',
      vosotros: 'quitaréis',
      ellos: 'quitarán',
    },
    imperative: {
      tu: 'quita',
      usted: 'quite',
      ustedes: 'quiten',
    },
    gerund: 'quitando',
    pastParticiple: {
      ms: 'quitado',
      fs: 'quitada',
      mp: 'quitados',
      fp: 'quitadas',
    },
  },

  toggle: {
    infinitive: 'alternar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'alterno',
      tu: 'alternas',
      el: 'alterna',
      nosotros: 'alternamos',
      vosotros: 'alternáis',
      ellos: 'alternan',
    },
    preterite: {
      yo: 'alterné',
      tu: 'alternaste',
      el: 'alternó',
      nosotros: 'alternamos',
      vosotros: 'alternasteis',
      ellos: 'alternaron',
    },
    imperfect: {
      yo: 'alternaba',
      tu: 'alternabas',
      el: 'alternaba',
      nosotros: 'alternábamos',
      vosotros: 'alternabais',
      ellos: 'alternaban',
    },
    future: {
      yo: 'alternaré',
      tu: 'alternarás',
      el: 'alternará',
      nosotros: 'alternaremos',
      vosotros: 'alternaréis',
      ellos: 'alternarán',
    },
    imperative: {
      tu: 'alterna',
      usted: 'alterne',
      ustedes: 'alternen',
    },
    gerund: 'alternando',
    pastParticiple: {
      ms: 'alternado',
      fs: 'alternada',
      mp: 'alternados',
      fp: 'alternadas',
    },
  },

  put: {
    infinitive: 'poner',
    verbClass: 'er',
    irregular: true,
    present: {
      yo: 'pongo',
      tu: 'pones',
      el: 'pone',
      nosotros: 'ponemos',
      vosotros: 'ponéis',
      ellos: 'ponen',
    },
    preterite: {
      yo: 'puse',
      tu: 'pusiste',
      el: 'puso',
      nosotros: 'pusimos',
      vosotros: 'pusisteis',
      ellos: 'pusieron',
    },
    imperfect: {
      yo: 'ponía',
      tu: 'ponías',
      el: 'ponía',
      nosotros: 'poníamos',
      vosotros: 'poníais',
      ellos: 'ponían',
    },
    future: {
      yo: 'pondré',
      tu: 'pondrás',
      el: 'pondrá',
      nosotros: 'pondremos',
      vosotros: 'pondréis',
      ellos: 'pondrán',
    },
    imperative: {
      tu: 'pon',
      usted: 'ponga',
      ustedes: 'pongan',
    },
    gerund: 'poniendo',
    pastParticiple: {
      ms: 'puesto',
      fs: 'puesta',
      mp: 'puestos',
      fp: 'puestas',
    },
  },

  set: {
    infinitive: 'establecer',
    verbClass: 'er',
    irregular: true,
    present: {
      yo: 'establezco',
      tu: 'estableces',
      el: 'establece',
      nosotros: 'establecemos',
      vosotros: 'establecéis',
      ellos: 'establecen',
    },
    preterite: {
      yo: 'establecí',
      tu: 'estableciste',
      el: 'estableció',
      nosotros: 'establecimos',
      vosotros: 'establecisteis',
      ellos: 'establecieron',
    },
    imperfect: {
      yo: 'establecía',
      tu: 'establecías',
      el: 'establecía',
      nosotros: 'establecíamos',
      vosotros: 'establecíais',
      ellos: 'establecían',
    },
    future: {
      yo: 'estableceré',
      tu: 'establecerás',
      el: 'establecerá',
      nosotros: 'estableceremos',
      vosotros: 'estableceréis',
      ellos: 'establecerán',
    },
    imperative: {
      tu: 'establece',
      usted: 'establezca',
      ustedes: 'establezcan',
    },
    gerund: 'estableciendo',
    pastParticiple: {
      ms: 'establecido',
      fs: 'establecida',
      mp: 'establecidos',
      fp: 'establecidas',
    },
  },

  show: {
    infinitive: 'mostrar',
    verbClass: 'ar',
    irregular: true,
    present: {
      yo: 'muestro',
      tu: 'muestras',
      el: 'muestra',
      nosotros: 'mostramos',
      vosotros: 'mostráis',
      ellos: 'muestran',
    },
    preterite: {
      yo: 'mostré',
      tu: 'mostraste',
      el: 'mostró',
      nosotros: 'mostramos',
      vosotros: 'mostrasteis',
      ellos: 'mostraron',
    },
    imperfect: {
      yo: 'mostraba',
      tu: 'mostrabas',
      el: 'mostraba',
      nosotros: 'mostrábamos',
      vosotros: 'mostrabais',
      ellos: 'mostraban',
    },
    future: {
      yo: 'mostraré',
      tu: 'mostrarás',
      el: 'mostrará',
      nosotros: 'mostraremos',
      vosotros: 'mostraréis',
      ellos: 'mostrarán',
    },
    imperative: {
      tu: 'muestra',
      usted: 'muestre',
      ustedes: 'muestren',
    },
    gerund: 'mostrando',
    pastParticiple: {
      ms: 'mostrado',
      fs: 'mostrada',
      mp: 'mostrados',
      fp: 'mostradas',
    },
  },

  hide: {
    infinitive: 'ocultar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'oculto',
      tu: 'ocultas',
      el: 'oculta',
      nosotros: 'ocultamos',
      vosotros: 'ocultáis',
      ellos: 'ocultan',
    },
    preterite: {
      yo: 'oculté',
      tu: 'ocultaste',
      el: 'ocultó',
      nosotros: 'ocultamos',
      vosotros: 'ocultasteis',
      ellos: 'ocultaron',
    },
    imperfect: {
      yo: 'ocultaba',
      tu: 'ocultabas',
      el: 'ocultaba',
      nosotros: 'ocultábamos',
      vosotros: 'ocultabais',
      ellos: 'ocultaban',
    },
    future: {
      yo: 'ocultaré',
      tu: 'ocultarás',
      el: 'ocultará',
      nosotros: 'ocultaremos',
      vosotros: 'ocultaréis',
      ellos: 'ocultarán',
    },
    imperative: {
      tu: 'oculta',
      usted: 'oculte',
      ustedes: 'oculten',
    },
    gerund: 'ocultando',
    pastParticiple: {
      ms: 'ocultado',
      fs: 'ocultada',
      mp: 'ocultados',
      fp: 'ocultadas',
    },
  },

  get: {
    infinitive: 'obtener',
    verbClass: 'er',
    irregular: true,
    present: {
      yo: 'obtengo',
      tu: 'obtienes',
      el: 'obtiene',
      nosotros: 'obtenemos',
      vosotros: 'obtenéis',
      ellos: 'obtienen',
    },
    preterite: {
      yo: 'obtuve',
      tu: 'obtuviste',
      el: 'obtuvo',
      nosotros: 'obtuvimos',
      vosotros: 'obtuvisteis',
      ellos: 'obtuvieron',
    },
    imperfect: {
      yo: 'obtenía',
      tu: 'obtenías',
      el: 'obtenía',
      nosotros: 'obteníamos',
      vosotros: 'obteníais',
      ellos: 'obtenían',
    },
    future: {
      yo: 'obtendré',
      tu: 'obtendrás',
      el: 'obtendrá',
      nosotros: 'obtendremos',
      vosotros: 'obtendréis',
      ellos: 'obtendrán',
    },
    imperative: {
      tu: 'obtén',
      usted: 'obtenga',
      ustedes: 'obtengan',
    },
    gerund: 'obteniendo',
    pastParticiple: {
      ms: 'obtenido',
      fs: 'obtenida',
      mp: 'obtenidos',
      fp: 'obtenidas',
    },
  },

  wait: {
    infinitive: 'esperar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'espero',
      tu: 'esperas',
      el: 'espera',
      nosotros: 'esperamos',
      vosotros: 'esperáis',
      ellos: 'esperan',
    },
    preterite: {
      yo: 'esperé',
      tu: 'esperaste',
      el: 'esperó',
      nosotros: 'esperamos',
      vosotros: 'esperasteis',
      ellos: 'esperaron',
    },
    imperfect: {
      yo: 'esperaba',
      tu: 'esperabas',
      el: 'esperaba',
      nosotros: 'esperábamos',
      vosotros: 'esperabais',
      ellos: 'esperaban',
    },
    future: {
      yo: 'esperaré',
      tu: 'esperarás',
      el: 'esperará',
      nosotros: 'esperaremos',
      vosotros: 'esperaréis',
      ellos: 'esperarán',
    },
    imperative: {
      tu: 'espera',
      usted: 'espere',
      ustedes: 'esperen',
    },
    gerund: 'esperando',
    pastParticiple: {
      ms: 'esperado',
      fs: 'esperada',
      mp: 'esperados',
      fp: 'esperadas',
    },
  },

  fetch: {
    infinitive: 'buscar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'busco',
      tu: 'buscas',
      el: 'busca',
      nosotros: 'buscamos',
      vosotros: 'buscáis',
      ellos: 'buscan',
    },
    preterite: {
      yo: 'busqué',
      tu: 'buscaste',
      el: 'buscó',
      nosotros: 'buscamos',
      vosotros: 'buscasteis',
      ellos: 'buscaron',
    },
    imperfect: {
      yo: 'buscaba',
      tu: 'buscabas',
      el: 'buscaba',
      nosotros: 'buscábamos',
      vosotros: 'buscabais',
      ellos: 'buscaban',
    },
    future: {
      yo: 'buscaré',
      tu: 'buscarás',
      el: 'buscará',
      nosotros: 'buscaremos',
      vosotros: 'buscaréis',
      ellos: 'buscarán',
    },
    imperative: {
      tu: 'busca',
      usted: 'busque',
      ustedes: 'busquen',
    },
    gerund: 'buscando',
    pastParticiple: {
      ms: 'buscado',
      fs: 'buscada',
      mp: 'buscados',
      fp: 'buscadas',
    },
  },

  send: {
    infinitive: 'enviar',
    verbClass: 'ar',
    irregular: true,
    present: {
      yo: 'envío',
      tu: 'envías',
      el: 'envía',
      nosotros: 'enviamos',
      vosotros: 'enviáis',
      ellos: 'envían',
    },
    preterite: {
      yo: 'envié',
      tu: 'enviaste',
      el: 'envió',
      nosotros: 'enviamos',
      vosotros: 'enviasteis',
      ellos: 'enviaron',
    },
    imperfect: {
      yo: 'enviaba',
      tu: 'enviabas',
      el: 'enviaba',
      nosotros: 'enviábamos',
      vosotros: 'enviabais',
      ellos: 'enviaban',
    },
    future: {
      yo: 'enviaré',
      tu: 'enviarás',
      el: 'enviará',
      nosotros: 'enviaremos',
      vosotros: 'enviaréis',
      ellos: 'enviarán',
    },
    imperative: {
      tu: 'envía',
      usted: 'envíe',
      ustedes: 'envíen',
    },
    gerund: 'enviando',
    pastParticiple: {
      ms: 'enviado',
      fs: 'enviada',
      mp: 'enviados',
      fp: 'enviadas',
    },
  },

  go: {
    infinitive: 'ir',
    verbClass: 'ir',
    irregular: true,
    present: {
      yo: 'voy',
      tu: 'vas',
      el: 'va',
      nosotros: 'vamos',
      vosotros: 'vais',
      ellos: 'van',
    },
    preterite: {
      yo: 'fui',
      tu: 'fuiste',
      el: 'fue',
      nosotros: 'fuimos',
      vosotros: 'fuisteis',
      ellos: 'fueron',
    },
    imperfect: {
      yo: 'iba',
      tu: 'ibas',
      el: 'iba',
      nosotros: 'íbamos',
      vosotros: 'ibais',
      ellos: 'iban',
    },
    future: {
      yo: 'iré',
      tu: 'irás',
      el: 'irá',
      nosotros: 'iremos',
      vosotros: 'iréis',
      ellos: 'irán',
    },
    imperative: {
      tu: 've',
      usted: 'vaya',
      ustedes: 'vayan',
    },
    gerund: 'yendo',
    pastParticiple: {
      ms: 'ido',
      fs: 'ida',
      mp: 'idos',
      fp: 'idas',
    },
  },

  increment: {
    infinitive: 'incrementar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'incremento',
      tu: 'incrementas',
      el: 'incrementa',
      nosotros: 'incrementamos',
      vosotros: 'incrementáis',
      ellos: 'incrementan',
    },
    preterite: {
      yo: 'incrementé',
      tu: 'incrementaste',
      el: 'incrementó',
      nosotros: 'incrementamos',
      vosotros: 'incrementasteis',
      ellos: 'incrementaron',
    },
    imperfect: {
      yo: 'incrementaba',
      tu: 'incrementabas',
      el: 'incrementaba',
      nosotros: 'incrementábamos',
      vosotros: 'incrementabais',
      ellos: 'incrementaban',
    },
    future: {
      yo: 'incrementaré',
      tu: 'incrementarás',
      el: 'incrementará',
      nosotros: 'incrementaremos',
      vosotros: 'incrementaréis',
      ellos: 'incrementarán',
    },
    imperative: {
      tu: 'incrementa',
      usted: 'incremente',
      ustedes: 'incrementen',
    },
    gerund: 'incrementando',
    pastParticiple: {
      ms: 'incrementado',
      fs: 'incrementada',
      mp: 'incrementados',
      fp: 'incrementadas',
    },
  },

  decrement: {
    infinitive: 'decrementar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'decremento',
      tu: 'decrementas',
      el: 'decrementa',
      nosotros: 'decrementamos',
      vosotros: 'decrementáis',
      ellos: 'decrementan',
    },
    preterite: {
      yo: 'decrementé',
      tu: 'decrementaste',
      el: 'decrementó',
      nosotros: 'decrementamos',
      vosotros: 'decrementasteis',
      ellos: 'decrementaron',
    },
    imperfect: {
      yo: 'decrementaba',
      tu: 'decrementabas',
      el: 'decrementaba',
      nosotros: 'decrementábamos',
      vosotros: 'decrementabais',
      ellos: 'decrementaban',
    },
    future: {
      yo: 'decrementaré',
      tu: 'decrementarás',
      el: 'decrementará',
      nosotros: 'decrementaremos',
      vosotros: 'decrementaréis',
      ellos: 'decrementarán',
    },
    imperative: {
      tu: 'decrementa',
      usted: 'decremente',
      ustedes: 'decrementen',
    },
    gerund: 'decrementando',
    pastParticiple: {
      ms: 'decrementado',
      fs: 'decrementada',
      mp: 'decrementados',
      fp: 'decrementadas',
    },
  },

  take: {
    infinitive: 'tomar',
    verbClass: 'ar',
    irregular: false,
    present: {
      yo: 'tomo',
      tu: 'tomas',
      el: 'toma',
      nosotros: 'tomamos',
      vosotros: 'tomáis',
      ellos: 'toman',
    },
    preterite: {
      yo: 'tomé',
      tu: 'tomaste',
      el: 'tomó',
      nosotros: 'tomamos',
      vosotros: 'tomasteis',
      ellos: 'tomaron',
    },
    imperfect: {
      yo: 'tomaba',
      tu: 'tomabas',
      el: 'tomaba',
      nosotros: 'tomábamos',
      vosotros: 'tomabais',
      ellos: 'tomaban',
    },
    future: {
      yo: 'tomaré',
      tu: 'tomarás',
      el: 'tomará',
      nosotros: 'tomaremos',
      vosotros: 'tomaréis',
      ellos: 'tomarán',
    },
    imperative: {
      tu: 'toma',
      usted: 'tome',
      ustedes: 'tomen',
    },
    gerund: 'tomando',
    pastParticiple: {
      ms: 'tomado',
      fs: 'tomada',
      mp: 'tomados',
      fp: 'tomadas',
    },
  },
};

const frames: LanguageFrames = {
  code: 'es',
  wordOrder: 'SVO',
  frames: [
    {
      function: 'commanding',
      template: '{verb.imperative.tu} {patient} {target}',
      verbForm: 'imperative.tu',
      example: 'agrega .active a #button',
    },
    {
      function: 'describing',
      template: '{subject} {verb.present.el} {patient} {target}',
      verbForm: 'present.el',
      example: 'El sistema agrega .active a #button',
    },
    {
      function: 'narrating',
      template: '{subject} {verb.preterite.el} {patient} {target}',
      verbForm: 'preterite.el',
      example: 'El sistema agregó .active a #button',
    },
    {
      function: 'questioning',
      template: '¿{verb.preterite.el} {subject} {patient} {target}?',
      verbForm: 'preterite.el',
      example: '¿Agregó el sistema .active a #button?',
    },
    {
      function: 'negating',
      template: '{subject} no {verb.preterite.el} {patient} {target}',
      verbForm: 'preterite.el',
      example: 'El sistema no agregó .active a #button',
    },
    {
      function: 'planning',
      template: '{subject} {verb.future.el} {patient} {target}',
      verbForm: 'future.el',
      example: 'El sistema agregará .active a #button',
    },
    {
      function: 'progressing',
      template: '{subject} está {verb.gerund} {patient} {target}',
      verbForm: 'gerund',
      example: 'El sistema está agregando .active a #button',
    },
  ],
};

export const esProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'es',
    wordOrder: 'SVO',
    keywords: {
      add: { primary: 'agregar', alternatives: ['agrega'] },
      remove: { primary: 'quitar', alternatives: ['quita'] },
      toggle: { primary: 'alternar', alternatives: ['alterna'] },
      put: { primary: 'poner', alternatives: ['pon'] },
      set: { primary: 'establecer', alternatives: ['establece'] },
      show: { primary: 'mostrar', alternatives: ['muestra'] },
      hide: { primary: 'ocultar', alternatives: ['oculta'] },
      get: { primary: 'obtener', alternatives: ['obtén'] },
      wait: { primary: 'esperar', alternatives: ['espera'] },
      fetch: { primary: 'buscar', alternatives: ['busca'] },
      send: { primary: 'enviar', alternatives: ['envía'] },
      go: { primary: 'ir', alternatives: ['ve'] },
      increment: { primary: 'incrementar', alternatives: ['incrementa'] },
      decrement: { primary: 'decrementar', alternatives: ['decrementa'] },
      take: { primary: 'tomar', alternatives: ['toma'] },
    },
  },
  morphologyTable,
  frames,
  defaultSubject: 'el sistema',
};
