import type { LearnLanguageProfile } from '../types';

export const jaProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'ja',
    wordOrder: 'SOV',
    keywords: {
      add: { primary: '追加' },
      remove: { primary: '削除' },
      toggle: { primary: '切り替え' },
      put: { primary: '置' },
      set: { primary: '設定' },
      show: { primary: '表示' },
      hide: { primary: '隠' },
      get: { primary: '取得' },
      wait: { primary: '待' },
      fetch: { primary: '取得' },
      send: { primary: '送' },
      go: { primary: '行' },
      increment: { primary: '増加' },
      decrement: { primary: '減少' },
      take: { primary: '取' },
    },
  },
  morphologyTable: {
    add: {
      dictionary: '追加する',
      verbClass: 'suru',
      stem: '追加し',
      masu: '追加します',
      mashita: '追加しました',
      ta: '追加した',
      te: '追加して',
      nai: '追加しない',
      masen: '追加しません',
      potential: '追加できる',
      volitional: '追加しよう',
      ba: '追加すれば',
      tara: '追加したら',
    },
    remove: {
      dictionary: '削除する',
      verbClass: 'suru',
      stem: '削除し',
      masu: '削除します',
      mashita: '削除しました',
      ta: '削除した',
      te: '削除して',
      nai: '削除しない',
      masen: '削除しません',
      potential: '削除できる',
      volitional: '削除しよう',
      ba: '削除すれば',
      tara: '削除したら',
    },
    toggle: {
      dictionary: '切り替える',
      verbClass: 'ichidan',
      stem: '切り替え',
      masu: '切り替えます',
      mashita: '切り替えました',
      ta: '切り替えた',
      te: '切り替えて',
      nai: '切り替えない',
      masen: '切り替えません',
      potential: '切り替えられる',
      volitional: '切り替えよう',
      ba: '切り替えれば',
      tara: '切り替えたら',
    },
    put: {
      dictionary: '置く',
      verbClass: 'godan',
      stem: '置き',
      masu: '置きます',
      mashita: '置きました',
      ta: '置いた',
      te: '置いて',
      nai: '置かない',
      masen: '置きません',
      potential: '置ける',
      volitional: '置こう',
      ba: '置けば',
      tara: '置いたら',
    },
    set: {
      dictionary: '設定する',
      verbClass: 'suru',
      stem: '設定し',
      masu: '設定します',
      mashita: '設定しました',
      ta: '設定した',
      te: '設定して',
      nai: '設定しない',
      masen: '設定しません',
      potential: '設定できる',
      volitional: '設定しよう',
      ba: '設定すれば',
      tara: '設定したら',
    },
    show: {
      dictionary: '表示する',
      verbClass: 'suru',
      stem: '表示し',
      masu: '表示します',
      mashita: '表示しました',
      ta: '表示した',
      te: '表示して',
      nai: '表示しない',
      masen: '表示しません',
      potential: '表示できる',
      volitional: '表示しよう',
      ba: '表示すれば',
      tara: '表示したら',
    },
    hide: {
      dictionary: '隠す',
      verbClass: 'godan',
      stem: '隠し',
      masu: '隠します',
      mashita: '隠しました',
      ta: '隠した',
      te: '隠して',
      nai: '隠さない',
      masen: '隠しません',
      potential: '隠せる',
      volitional: '隠そう',
      ba: '隠せば',
      tara: '隠したら',
    },
    get: {
      dictionary: '取得する',
      verbClass: 'suru',
      stem: '取得し',
      masu: '取得します',
      mashita: '取得しました',
      ta: '取得した',
      te: '取得して',
      nai: '取得しない',
      masen: '取得しません',
      potential: '取得できる',
      volitional: '取得しよう',
      ba: '取得すれば',
      tara: '取得したら',
    },
    wait: {
      dictionary: '待つ',
      verbClass: 'godan',
      stem: '待ち',
      masu: '待ちます',
      mashita: '待ちました',
      ta: '待った',
      te: '待って',
      nai: '待たない',
      masen: '待ちません',
      potential: '待てる',
      volitional: '待とう',
      ba: '待てば',
      tara: '待ったら',
    },
    fetch: {
      dictionary: '取得する',
      verbClass: 'suru',
      stem: '取得し',
      masu: '取得します',
      mashita: '取得しました',
      ta: '取得した',
      te: '取得して',
      nai: '取得しない',
      masen: '取得しません',
      potential: '取得できる',
      volitional: '取得しよう',
      ba: '取得すれば',
      tara: '取得したら',
    },
    send: {
      dictionary: '送る',
      verbClass: 'godan',
      stem: '送り',
      masu: '送ります',
      mashita: '送りました',
      ta: '送った',
      te: '送って',
      nai: '送らない',
      masen: '送りません',
      potential: '送れる',
      volitional: '送ろう',
      ba: '送れば',
      tara: '送ったら',
    },
    go: {
      dictionary: '行く',
      verbClass: 'godan',
      stem: '行き',
      masu: '行きます',
      mashita: '行きました',
      ta: '行った',
      te: '行って',
      nai: '行かない',
      masen: '行きません',
      potential: '行ける',
      volitional: '行こう',
      ba: '行けば',
      tara: '行ったら',
    },
    increment: {
      dictionary: '増加する',
      verbClass: 'suru',
      stem: '増加し',
      masu: '増加します',
      mashita: '増加しました',
      ta: '増加した',
      te: '増加して',
      nai: '増加しない',
      masen: '増加しません',
      potential: '増加できる',
      volitional: '増加しよう',
      ba: '増加すれば',
      tara: '増加したら',
    },
    decrement: {
      dictionary: '減少する',
      verbClass: 'suru',
      stem: '減少し',
      masu: '減少します',
      mashita: '減少しました',
      ta: '減少した',
      te: '減少して',
      nai: '減少しない',
      masen: '減少しません',
      potential: '減少できる',
      volitional: '減少しよう',
      ba: '減少すれば',
      tara: '減少したら',
    },
    take: {
      dictionary: '取る',
      verbClass: 'godan',
      stem: '取り',
      masu: '取ります',
      mashita: '取りました',
      ta: '取った',
      te: '取って',
      nai: '取らない',
      masen: '取りません',
      potential: '取れる',
      volitional: '取ろう',
      ba: '取れば',
      tara: '取ったら',
    },
  },
  frames: {
    code: 'ja',
    wordOrder: 'SOV',
    frames: [
      {
        function: 'commanding',
        template: '{target} {patient} {verb.te}',
        verbForm: 'te',
        example: '#buttonに .activeを 追加して',
      },
      {
        function: 'describing',
        template: '{subject}は {target} {patient} {verb.masu}',
        verbForm: 'masu',
        example: 'システムは #buttonに .activeを 追加します',
      },
      {
        function: 'narrating',
        template: '{subject}は {target} {patient} {verb.mashita}',
        verbForm: 'mashita',
        example: 'システムは #buttonに .activeを 追加しました',
      },
      {
        function: 'questioning',
        template: '{subject}は {target} {patient} {verb.mashita}か？',
        verbForm: 'mashita',
        example: 'システムは #buttonに .activeを 追加しましたか？',
      },
      {
        function: 'negating',
        template: '{subject}は {target} {patient} {verb.masen}でした',
        verbForm: 'masen',
        example: 'システムは #buttonに .activeを 追加しませんでした',
      },
      {
        function: 'planning',
        template: '{target} {patient} {verb.volitional}',
        verbForm: 'volitional',
        example: '#buttonに .activeを 追加しよう',
      },
      {
        function: 'progressing',
        template: '{target} {patient} {verb.ba}',
        verbForm: 'ba',
        example: '#buttonに .activeを 追加すれば',
      },
    ],
  },
  defaultSubject: 'システム',
};
