import type { LearnLanguageProfile } from '../types';

export const koProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'ko',
    wordOrder: 'SOV',
    keywords: {
      add: { primary: '추가' },
      remove: { primary: '제거' },
      toggle: { primary: '토글' },
      put: { primary: '넣' },
      set: { primary: '설정' },
      show: { primary: '보이' },
      hide: { primary: '숨기' },
      get: { primary: '얻' },
      wait: { primary: '대기' },
      fetch: { primary: '패치' },
      send: { primary: '보내' },
      go: { primary: '이동' },
      increment: { primary: '증가' },
      decrement: { primary: '감소' },
      take: { primary: '가져오' },
    },
  },
  morphologyTable: {
    add: {
      dictionary: '추가하다',
      verbClass: 'hada',
      stem: '추가하',
      hapnida: '추가합니다',
      haesseumnida: '추가했습니다',
      haeyo: '추가해요',
      haesseoyo: '추가했어요',
      imperative: '추가하세요',
      past: '추가했다',
      negative: '추가하지 않다',
      progressive: '추가하고 있다',
      future: '추가할 것이다',
    },
    remove: {
      dictionary: '제거하다',
      verbClass: 'hada',
      stem: '제거하',
      hapnida: '제거합니다',
      haesseumnida: '제거했습니다',
      haeyo: '제거해요',
      haesseoyo: '제거했어요',
      imperative: '제거하세요',
      past: '제거했다',
      negative: '제거하지 않다',
      progressive: '제거하고 있다',
      future: '제거할 것이다',
    },
    toggle: {
      dictionary: '토글하다',
      verbClass: 'hada',
      stem: '토글하',
      hapnida: '토글합니다',
      haesseumnida: '토글했습니다',
      haeyo: '토글해요',
      haesseoyo: '토글했어요',
      imperative: '토글하세요',
      past: '토글했다',
      negative: '토글하지 않다',
      progressive: '토글하고 있다',
      future: '토글할 것이다',
    },
    put: {
      dictionary: '넣다',
      verbClass: 'native',
      stem: '넣',
      hapnida: '넣습니다',
      haesseumnida: '넣었습니다',
      haeyo: '넣어요',
      haesseoyo: '넣었어요',
      imperative: '넣으세요',
      past: '넣었다',
      negative: '넣지 않다',
      progressive: '넣고 있다',
      future: '넣을 것이다',
    },
    set: {
      dictionary: '설정하다',
      verbClass: 'hada',
      stem: '설정하',
      hapnida: '설정합니다',
      haesseumnida: '설정했습니다',
      haeyo: '설정해요',
      haesseoyo: '설정했어요',
      imperative: '설정하세요',
      past: '설정했다',
      negative: '설정하지 않다',
      progressive: '설정하고 있다',
      future: '설정할 것이다',
    },
    show: {
      dictionary: '보이다',
      verbClass: 'native',
      stem: '보이',
      hapnida: '보입니다',
      haesseumnida: '보였습니다',
      haeyo: '보여요',
      haesseoyo: '보였어요',
      imperative: '보이세요',
      past: '보였다',
      negative: '보이지 않다',
      progressive: '보이고 있다',
      future: '보일 것이다',
    },
    hide: {
      dictionary: '숨기다',
      verbClass: 'native',
      stem: '숨기',
      hapnida: '숨깁니다',
      haesseumnida: '숨겼습니다',
      haeyo: '숨겨요',
      haesseoyo: '숨겼어요',
      imperative: '숨기세요',
      past: '숨겼다',
      negative: '숨기지 않다',
      progressive: '숨기고 있다',
      future: '숨길 것이다',
    },
    get: {
      dictionary: '얻다',
      verbClass: 'native',
      stem: '얻',
      hapnida: '얻습니다',
      haesseumnida: '얻었습니다',
      haeyo: '얻어요',
      haesseoyo: '얻었어요',
      imperative: '얻으세요',
      past: '얻었다',
      negative: '얻지 않다',
      progressive: '얻고 있다',
      future: '얻을 것이다',
    },
    wait: {
      dictionary: '대기하다',
      verbClass: 'hada',
      stem: '대기하',
      hapnida: '대기합니다',
      haesseumnida: '대기했습니다',
      haeyo: '대기해요',
      haesseoyo: '대기했어요',
      imperative: '대기하세요',
      past: '대기했다',
      negative: '대기하지 않다',
      progressive: '대기하고 있다',
      future: '대기할 것이다',
    },
    fetch: {
      dictionary: '패치하다',
      verbClass: 'hada',
      stem: '패치하',
      hapnida: '패치합니다',
      haesseumnida: '패치했습니다',
      haeyo: '패치해요',
      haesseoyo: '패치했어요',
      imperative: '패치하세요',
      past: '패치했다',
      negative: '패치하지 않다',
      progressive: '패치하고 있다',
      future: '패치할 것이다',
    },
    send: {
      dictionary: '보내다',
      verbClass: 'native',
      stem: '보내',
      hapnida: '보냅니다',
      haesseumnida: '보냈습니다',
      haeyo: '보내요',
      haesseoyo: '보냈어요',
      imperative: '보내세요',
      past: '보냈다',
      negative: '보내지 않다',
      progressive: '보내고 있다',
      future: '보낼 것이다',
    },
    go: {
      dictionary: '이동하다',
      verbClass: 'hada',
      stem: '이동하',
      hapnida: '이동합니다',
      haesseumnida: '이동했습니다',
      haeyo: '이동해요',
      haesseoyo: '이동했어요',
      imperative: '이동하세요',
      past: '이동했다',
      negative: '이동하지 않다',
      progressive: '이동하고 있다',
      future: '이동할 것이다',
    },
    increment: {
      dictionary: '증가하다',
      verbClass: 'hada',
      stem: '증가하',
      hapnida: '증가합니다',
      haesseumnida: '증가했습니다',
      haeyo: '증가해요',
      haesseoyo: '증가했어요',
      imperative: '증가하세요',
      past: '증가했다',
      negative: '증가하지 않다',
      progressive: '증가하고 있다',
      future: '증가할 것이다',
    },
    decrement: {
      dictionary: '감소하다',
      verbClass: 'hada',
      stem: '감소하',
      hapnida: '감소합니다',
      haesseumnida: '감소했습니다',
      haeyo: '감소해요',
      haesseoyo: '감소했어요',
      imperative: '감소하세요',
      past: '감소했다',
      negative: '감소하지 않다',
      progressive: '감소하고 있다',
      future: '감소할 것이다',
    },
    take: {
      dictionary: '가져오다',
      verbClass: 'native',
      stem: '가져오',
      hapnida: '가져옵니다',
      haesseumnida: '가져왔습니다',
      haeyo: '가져와요',
      haesseoyo: '가져왔어요',
      imperative: '가져오세요',
      past: '가져왔다',
      negative: '가져오지 않다',
      progressive: '가져오고 있다',
      future: '가져올 것이다',
    },
  },
  frames: {
    code: 'ko',
    wordOrder: 'SOV',
    frames: [
      {
        function: 'commanding',
        template: '{target} {patient} {verb.imperative}',
        verbForm: 'imperative',
        example: '#button에 .active를 추가하세요',
      },
      {
        function: 'describing',
        template: '{subject}은 {target} {patient} {verb.hapnida}',
        verbForm: 'hapnida',
        example: '시스템은 #button에 .active를 추가합니다',
      },
      {
        function: 'narrating',
        template: '{subject}은 {target} {patient} {verb.haesseumnida}',
        verbForm: 'haesseumnida',
        example: '시스템은 #button에 .active를 추가했습니다',
      },
      {
        function: 'questioning',
        template: '{subject}은 {target} {patient} {verb.haesseumnida}?',
        verbForm: 'haesseumnida',
        example: '시스템은 #button에 .active를 추가했습니까?',
      },
      {
        function: 'negating',
        template: '{subject}은 {target} {patient} {verb.negative}',
        verbForm: 'negative',
        example: '시스템은 #button에 .active를 추가하지 않다',
      },
      {
        function: 'planning',
        template: '{target} {patient} {verb.future}',
        verbForm: 'future',
        example: '#button에 .active를 추가할 것이다',
      },
      {
        function: 'progressing',
        template: '{target} {patient} {verb.progressive}',
        verbForm: 'progressive',
        example: '#button에 .active를 추가하고 있다',
      },
    ],
  },
  defaultSubject: '시스템',
};
