import type { LearnLanguageProfile } from '../types';

export const zhProfile: LearnLanguageProfile = {
  patternProfile: {
    code: 'zh',
    wordOrder: 'SVO',
    keywords: {
      add: { primary: '添加' },
      remove: { primary: '移除' },
      toggle: { primary: '切换' },
      put: { primary: '放置' },
      set: { primary: '设置' },
      show: { primary: '显示' },
      hide: { primary: '隐藏' },
      get: { primary: '获取' },
      wait: { primary: '等待' },
      fetch: { primary: '抓取' },
      send: { primary: '发送' },
      go: { primary: '前往' },
      increment: { primary: '增加' },
      decrement: { primary: '减少' },
      take: { primary: '拿取' },
    },
  },
  morphologyTable: {
    add: {
      base: '添加',
      pinyin: 'tiān jiā',
      patterns: {
        completed: '添加了',
        experience: '添加过',
        progressive: '在添加',
        future: '会添加',
        negPresent: '不添加',
        negPast: '没添加',
      },
    },
    remove: {
      base: '移除',
      pinyin: 'yí chú',
      patterns: {
        completed: '移除了',
        experience: '移除过',
        progressive: '在移除',
        future: '会移除',
        negPresent: '不移除',
        negPast: '没移除',
      },
    },
    toggle: {
      base: '切换',
      pinyin: 'qiē huàn',
      patterns: {
        completed: '切换了',
        experience: '切换过',
        progressive: '在切换',
        future: '会切换',
        negPresent: '不切换',
        negPast: '没切换',
      },
    },
    put: {
      base: '放置',
      pinyin: 'fàng zhì',
      patterns: {
        completed: '放置了',
        experience: '放置过',
        progressive: '在放置',
        future: '会放置',
        negPresent: '不放置',
        negPast: '没放置',
      },
    },
    set: {
      base: '设置',
      pinyin: 'shè zhì',
      patterns: {
        completed: '设置了',
        experience: '设置过',
        progressive: '在设置',
        future: '会设置',
        negPresent: '不设置',
        negPast: '没设置',
      },
    },
    show: {
      base: '显示',
      pinyin: 'xiǎn shì',
      patterns: {
        completed: '显示了',
        experience: '显示过',
        progressive: '在显示',
        future: '会显示',
        negPresent: '不显示',
        negPast: '没显示',
      },
    },
    hide: {
      base: '隐藏',
      pinyin: 'yǐn cáng',
      patterns: {
        completed: '隐藏了',
        experience: '隐藏过',
        progressive: '在隐藏',
        future: '会隐藏',
        negPresent: '不隐藏',
        negPast: '没隐藏',
      },
    },
    get: {
      base: '获取',
      pinyin: 'huò qǔ',
      patterns: {
        completed: '获取了',
        experience: '获取过',
        progressive: '在获取',
        future: '会获取',
        negPresent: '不获取',
        negPast: '没获取',
      },
    },
    wait: {
      base: '等待',
      pinyin: 'děng dài',
      patterns: {
        completed: '等待了',
        experience: '等待过',
        progressive: '在等待',
        future: '会等待',
        negPresent: '不等待',
        negPast: '没等待',
      },
    },
    fetch: {
      base: '抓取',
      pinyin: 'zhuā qǔ',
      patterns: {
        completed: '抓取了',
        experience: '抓取过',
        progressive: '在抓取',
        future: '会抓取',
        negPresent: '不抓取',
        negPast: '没抓取',
      },
    },
    send: {
      base: '发送',
      pinyin: 'fā sòng',
      patterns: {
        completed: '发送了',
        experience: '发送过',
        progressive: '在发送',
        future: '会发送',
        negPresent: '不发送',
        negPast: '没发送',
      },
    },
    go: {
      base: '前往',
      pinyin: 'qián wǎng',
      patterns: {
        completed: '前往了',
        experience: '前往过',
        progressive: '在前往',
        future: '会前往',
        negPresent: '不前往',
        negPast: '没前往',
      },
    },
    increment: {
      base: '增加',
      pinyin: 'zēng jiā',
      patterns: {
        completed: '增加了',
        experience: '增加过',
        progressive: '在增加',
        future: '会增加',
        negPresent: '不增加',
        negPast: '没增加',
      },
    },
    decrement: {
      base: '减少',
      pinyin: 'jiǎn shǎo',
      patterns: {
        completed: '减少了',
        experience: '减少过',
        progressive: '在减少',
        future: '会减少',
        negPresent: '不减少',
        negPast: '没减少',
      },
    },
    take: {
      base: '拿取',
      pinyin: 'ná qǔ',
      patterns: {
        completed: '拿取了',
        experience: '拿取过',
        progressive: '在拿取',
        future: '会拿取',
        negPresent: '不拿取',
        negPast: '没拿取',
      },
    },
  },
  frames: {
    code: 'zh',
    wordOrder: 'SVO',
    frames: [
      {
        function: 'commanding',
        template: '把 {patient} {verb.base} {target}',
        verbForm: 'base',
        example: '把 .active 添加 到 #button',
      },
      {
        function: 'describing',
        template: '{subject} {verb.base} {patient} {target}',
        verbForm: 'base',
        example: '系统 添加 .active 到 #button',
      },
      {
        function: 'narrating',
        template: '{subject} {verb.patterns.completed} {patient} {target}',
        verbForm: 'patterns.completed',
        example: '系统 添加了 .active 到 #button',
      },
      {
        function: 'questioning',
        template: '{subject} {verb.patterns.completed} {patient} {target} 吗？',
        verbForm: 'patterns.completed',
        example: '系统 添加了 .active 到 #button 吗？',
      },
      {
        function: 'negating',
        template: '{subject} {verb.patterns.negPast} {patient} {target}',
        verbForm: 'patterns.negPast',
        example: '系统 没添加 .active 到 #button',
      },
      {
        function: 'planning',
        template: '{subject} {verb.patterns.future} {patient} {target}',
        verbForm: 'patterns.future',
        example: '系统 会添加 .active 到 #button',
      },
      {
        function: 'progressing',
        template: '{subject} {verb.patterns.progressive} {patient} {target}',
        verbForm: 'patterns.progressive',
        example: '系统 在添加 .active 到 #button',
      },
    ],
  },
  defaultSubject: '系统',
};
